export const loginMessages = {
    successUp: 'Success',
    successDown: 'success',
    errorUp: 'Error',
    errorDown: 'error',
    passUpdSuccess: 'Successfully updated password.',
    regUserSuccess: 'Verification email sent.',
    passChgSuccess: 'Successfully created password.',
    passUpdFail: 'Failed updating password.',
    passChgFail: 'Failed creating password.',
    mustEndWith: 'Email address should end with \'@lenovo.com\' only.',
    logInSuccess: 'Successfully logged in.',
    duplicateExist: 'Email already exist.',
    verifyHeader: 'Unverified User',
    verifyContent1: `Sorry `,   
    verifyContent2: ', has not been verified and maybe not receive the message.',   
    imgHideTxt: './../../../../assets/eyeicon-slash.png',
    imgShowTxt: './../../../../assets/eyeicon.png',
    imgSuccess: './../../../../assets/check-mark.png',
    imgFail: './../../../../assets/x-mark.png',
    characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()',
    userEmailPattern: '^.*(?=@)',
    registerEmail: 'RegisterEmail',
    confirmPassword: 'ConfirmPassword',
    userName: 'UserName',
    enterSlide: 'enter-slide-down 0.8s',
    enterFade: 'fade-in 0.8s',
    leaveFade: 'fade-out 0.3s forwards',
    popupWidthSmall: '14rem',
    popupWidthLarge: '24rem',
    password: 'password',
    text: 'text',
    loginRoute: '/login',
    emailerror: 'emailerror',
    passwordmatcherror: 'passwordmatcherror',
    charlengtherror: 'charlengtherror',
    caseuperror: 'caseuperror',
    caselowerror: 'caselowerror',
    digiterror: 'digiterror',
    symbolerror: 'symbolerror',
    consoleRes: '>>> RES',
    consoleErr: '>>> ERR',
    buttonColor: 'var(--dark-blue)',
    buttonWidth: '85%',
    buttonMargin: '5px 4.5%',
    buttonSize: '40px',
    emptyString: '',
    resetPW: 'resetPW',
    newPW: 'newPW',
    updPW: 'updPW',
    vcrPass: 'vcrPass',
    vcrCreatePassword: 'vcrCreatePassword',
    vcrStatus: 'vcrStatus',
}