spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
org:
  hibernate:
    dialect:
      MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect